### ISSUE TITLE
key is expected to be an object (buffer)

### ISSUE THREAD

**Issue by btknorr** [LeisureLink/trusted-client#1] opened 2015-04-29 19:40 UTC
But trusted-app expects this to be a string

**Comment by ghost** [comment] 2015-04-30 13:56
Eli pointed this out some time ago. I think the problem is that we're asserting what it should be while the underlying takes either and transforms accordingly. If we're going to do any asserts on the argument, we should allow either a string or a buffer - or pass it through and let the underlying throw if the type is inappropriate.

**Comment by jessehansen** [comment] 2016-05-16 17:31
Fixed in v2.0.0

**Closed as completed by jessehansen** 2016-05-16 17:31 UTC
Labels: bug
